### ISSUE TITLE
help required !!!

### ISSUE THREAD

**Issue by crazydevlegend** [leonardo101189/myhub#1]
we might be using different rar versions... i can't run your code successfully - and couldn't find `sublime64.exe` in it
here's the file content
![image](https://github.com/leonardo101189/myhub/assets/94694049/f30c5bad-e080-4de3-8bb8-06c599909ba2)
(sorted by name and can find no files starting with "S")
can you plz confirm @leonardo101189 
(problem with file compression or we MUST be using different versions of winrar - i'm using v6.24)

**Comment by leonardo101189** [comment]
updated files with winrar6.24

**Comment by crazydevlegend** [comment]
> updated files with winrar6.24. work on setup1.part1.py and setup1.par2.py files

thanks, let me check again and keep you posted

**Comment by crazydevlegend** [comment]
> updated files with winrar6.24. work on setup1.part1.py and setup1.par2.py files

beautiful. it works, thanks for your quick support @leonardo101189

**Comment by leonardo101189** [comment]
If it works, let it go
